### ISSUE TITLE
Same example sample in both training and imputing 

### ISSUE THREAD

**Issue by NTNguyen13** [tatsuhikonaito/DEEP-HLA#5]
Hi, I'm trying out DEEP-HLA after reading your paper on Nat. Comm.

I'm trying to follow the example data, I found that step 1. Model training and step 2. Imputation both use the option `--sample`, and use the same sample `1958BC`.

I'm not so clear about the usage of that option. From my understanding, step 1 uses sample 1958BC for validation in training, and step 2 uses sample 1958BC for testing. Am I right? 

As I understand, In case that I have my own dataset, say 1000 sequencing samples, I can take out 900 samples to build a training set, 100 samples for testing (both in step 1). Then I genotyped 500 more samples and just input them in step 2.

Please help me to understand this use case, thank you very much.

**Comment by tatsuhikonaito** [comment]
I apologize for the delayed response.

In step 1, the data to be trained (a reference panel) is indicated by the option --ref. The option --sample (bim file) is used just to select SNPs that exist both in the reference panel and sample data used in step2.

In your case, are HLA alleles and SNPs sequenced in the 1000 samples? If I understand your situation correctly, you should use the 1000 samples for training with the option --sample to specifiy the bim file prefix of the 500 remaining data.
Please tell me if you have any additional questions.

Best

**Comment by NTNguyen13** [comment]
Thank you!

I also have some questions about making the Reference (.bim/.bed/.fam). As I see from the example, I can use the SNP2HLA MakeReference package to create it, I can create hla.ped, .bim/.bed/.fam files, but they have 4 HLA Dictionary files I don't know how to make. I have contacted SNP2HLA group at Broad Institute, but they haven't responded for a long time.

![image](https://user-images.githubusercontent.com/39985901/138392135-dcfd605c-cb14-4b44-ba02-dc8aef449282.png)

Could you please show me how to make the reference for DEEP*HLA?
